- name: Install vim and jq packages on all servers
  hosts: all
  become: yes # To become root inside the server to execute sudo apt...
  
  vars:
    packages:
    - vim
    - nano
  
  roles:
  - role: roles/packages